/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    services: Service;
    'contact-submissions': ContactSubmission;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'services-page': ServicesPage;
    'projects-page': ProjectsPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Portfolio projects shown on the Projects page; the first three (by display order) are featured on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Used for direct links, e.g. /projects#my-project.
   */
  slug: string;
  category: 'Residential' | 'Commercial' | 'Infrastructure';
  location: string;
  /**
   * Year the project started or was delivered, e.g. 2024.
   */
  year: string;
  status: 'Completed' | 'Ongoing';
  description: string;
  /**
   * Main project photo shown on the card. Leave empty for a styled placeholder.
   */
  coverImage?: (number | null) | Media;
  /**
   * Up to three key figures shown on the project card.
   */
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Service lines shown on the Services page, the homepage, and the contact form's service dropdown.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Used for direct links, e.g. /services#my-service.
   */
  slug: string;
  summary: string;
  /**
   * Photo shown alongside this service. Leave empty for a styled placeholder.
   */
  image?: (number | null) | Media;
  /**
   * Bullet points listed under the service.
   */
  details?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inquiries sent through the website's contact form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Service the visitor selected in the form.
   */
  service?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  location?: T;
  year?: T;
  status?: T;
  description?: T;
  coverImage?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  image?: T;
  details?:
    | T
    | {
        item?: T;
        id?: T;
      };
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Company-wide content: brand name, navigation, contact details, stats, and footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brand: {
    /**
     * First part of the logo text (white).
     */
    name: string;
    /**
     * Second part of the logo text (amber).
     */
    accent: string;
  };
  /**
   * Menu items in the header. The page address must match an existing page (/, /about, /services, /projects, /contact).
   */
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used in the footer and on the Contact page.
   */
  contact: {
    address: string;
    phone: string;
    email: string;
    /**
     * One-line version shown in the footer.
     */
    hoursShort: string;
    /**
     * Shown on the Contact page; each line becomes its own row.
     */
    hoursLines: string;
  };
  /**
   * Company stats shown on the homepage and About page.
   */
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  footer: {
    description: string;
    quickLinksTitle: string;
    contactTitle: string;
    /**
     * Shown after the year, e.g. © 2026 <this text>.
     */
    copyright: string;
  };
  siteMeta: {
    /**
     * Default browser-tab title (used on the homepage).
     */
    title: string;
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow: string;
    /**
     * Main headline (white part).
     */
    title: string;
    /**
     * Last words of the headline, shown in amber.
     */
    titleAccent: string;
    description: string;
    primaryCtaLabel: string;
    secondaryCtaLabel: string;
    /**
     * Optional hero background photo (a wide, high-quality project image works best). Leave empty for the dark blueprint pattern.
     */
    backgroundImage?: (number | null) | Media;
  };
  servicesSection: {
    eyebrow: string;
    title: string;
  };
  projectsSection: {
    eyebrow: string;
    title: string;
    allProjectsLabel: string;
  };
  whySection: {
    eyebrow: string;
    title: string;
    body: string;
    ctaLabel: string;
    points?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    title: string;
    text: string;
    buttonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  meta: {
    /**
     * Shown in the browser tab and search results.
     */
    title: string;
    description: string;
  };
  hero: {
    eyebrow: string;
    title: string;
    description: string;
    /**
     * Optional background photo behind this page's header. Leave empty for the dark blueprint pattern.
     */
    backgroundImage?: (number | null) | Media;
  };
  story: {
    eyebrow: string;
    title: string;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  mission: {
    title: string;
    text: string;
  };
  vision: {
    title: string;
    text: string;
  };
  valuesSection: {
    eyebrow: string;
    title: string;
    items?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  teamSection: {
    eyebrow: string;
    title: string;
    members?:
      | {
          name: string;
          role: string;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    title: string;
    buttonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  meta: {
    /**
     * Shown in the browser tab and search results.
     */
    title: string;
    description: string;
  };
  hero: {
    eyebrow: string;
    title: string;
    description: string;
    /**
     * Optional background photo behind this page's header. Leave empty for the dark blueprint pattern.
     */
    backgroundImage?: (number | null) | Media;
  };
  cta: {
    title: string;
    text: string;
    buttonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  meta: {
    /**
     * Shown in the browser tab and search results.
     */
    title: string;
    description: string;
  };
  hero: {
    eyebrow: string;
    title: string;
    description: string;
    /**
     * Optional background photo behind this page's header. Leave empty for the dark blueprint pattern.
     */
    backgroundImage?: (number | null) | Media;
  };
  cta: {
    title: string;
    buttonLabel: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  meta: {
    /**
     * Shown in the browser tab and search results.
     */
    title: string;
    description: string;
  };
  hero: {
    eyebrow: string;
    title: string;
    description: string;
    /**
     * Optional background photo behind this page's header. Leave empty for the dark blueprint pattern.
     */
    backgroundImage?: (number | null) | Media;
  };
  /**
   * Headings for the contact details column. The values themselves (address, phone…) are edited in Site Settings.
   */
  detailLabels: {
    office: string;
    phone: string;
    email: string;
    hours: string;
  };
  /**
   * Caption shown beneath the office-location map.
   */
  mapPlaceholder: string;
  /**
   * Paste a map 'embed' URL to show your exact office location. In Google Maps: Share → Embed a map → copy the src="…" link. Leave empty to show a default Addis Ababa map.
   */
  mapEmbedUrl?: string | null;
  formSection: {
    title: string;
    intro: string;
  };
  /**
   * Labels and texts of the inquiry form.
   */
  form: {
    nameLabel: string;
    namePlaceholder: string;
    emailLabel: string;
    emailPlaceholder: string;
    phoneLabel: string;
    phonePlaceholder: string;
    serviceLabel: string;
    servicePlaceholder: string;
    otherServiceOption: string;
    messageLabel: string;
    messagePlaceholder: string;
    submitLabel: string;
    successTitle: string;
    successText: string;
    /**
     * Shown if the inquiry could not be sent.
     */
    errorText: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        accent?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        address?: T;
        phone?: T;
        email?: T;
        hoursShort?: T;
        hoursLines?: T;
      };
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        description?: T;
        quickLinksTitle?: T;
        contactTitle?: T;
        copyright?: T;
      };
  siteMeta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        titleAccent?: T;
        description?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        backgroundImage?: T;
      };
  servicesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  projectsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        allProjectsLabel?: T;
      };
  whySection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        ctaLabel?: T;
        points?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
      };
  story?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  mission?:
    | T
    | {
        title?: T;
        text?: T;
      };
  vision?:
    | T
    | {
        title?: T;
        text?: T;
      };
  valuesSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  teamSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        backgroundImage?: T;
      };
  detailLabels?:
    | T
    | {
        office?: T;
        phone?: T;
        email?: T;
        hours?: T;
      };
  mapPlaceholder?: T;
  mapEmbedUrl?: T;
  formSection?:
    | T
    | {
        title?: T;
        intro?: T;
      };
  form?:
    | T
    | {
        nameLabel?: T;
        namePlaceholder?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        phoneLabel?: T;
        phonePlaceholder?: T;
        serviceLabel?: T;
        servicePlaceholder?: T;
        otherServiceOption?: T;
        messageLabel?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        successTitle?: T;
        successText?: T;
        errorText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}